export const USER_DATA = [
  { id: 1, firstName: "John", lastName: "Doe", email: "johndoe@example.com" },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Johnson",
    email: "mjohnson@example.com",
  },
  { id: 4, firstName: "Emily", lastName: "Davis", email: "edavis@example.com" },
  { id: 5, firstName: "Chris", lastName: "Brown", email: "cbrown@example.com" },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Wilson",
    email: "swilson@example.com",
  },
  {
    id: 7,
    firstName: "David",
    lastName: "Martinez",
    email: "dmartinez@example.com",
  },
  {
    id: 8,
    firstName: "Jessica",
    lastName: "Garcia",
    email: "jgarcia@example.com",
  },
  {
    id: 9,
    firstName: "Matthew",
    lastName: "Martinez",
    email: "mmartinez@example.com",
  },
  {
    id: 10,
    firstName: "Ashley",
    lastName: "Rodriguez",
    email: "arodriguez@example.com",
  },
  {
    id: 11,
    firstName: "Joshua",
    lastName: "Perez",
    email: "jperez@example.com",
  },
  {
    id: 12,
    firstName: "Megan",
    lastName: "Hernandez",
    email: "mhernandez@example.com",
  },
  { id: 13, firstName: "Andrew", lastName: "King", email: "aking@example.com" },
  {
    id: 14,
    firstName: "Sophia",
    lastName: "Scott",
    email: "sscott@example.com",
  },
  {
    id: 15,
    firstName: "Daniel",
    lastName: "Green",
    email: "dgreen@example.com",
  },
  {
    id: 16,
    firstName: "Olivia",
    lastName: "Baker",
    email: "obaker@example.com",
  },
  {
    id: 17,
    firstName: "James",
    lastName: "Gonzalez",
    email: "jgonzalez@example.com",
  },
  {
    id: 18,
    firstName: "Isabella",
    lastName: "Nelson",
    email: "inelson@example.com",
  },
  {
    id: 19,
    firstName: "Anthony",
    lastName: "Carter",
    email: "acarter@example.com",
  },
  {
    id: 20,
    firstName: "Ava",
    lastName: "Mitchell",
    email: "amitchell@example.com",
  },
  {
    id: 21,
    firstName: "Robert",
    lastName: "Perez",
    email: "rperez@example.com",
  },
  {
    id: 22,
    firstName: "Emma",
    lastName: "Roberts",
    email: "eroberts@example.com",
  },
  {
    id: 23,
    firstName: "William",
    lastName: "Turner",
    email: "wturner@example.com",
  },
  {
    id: 24,
    firstName: "Mia",
    lastName: "Phillips",
    email: "mphillips@example.com",
  },
  {
    id: 25,
    firstName: "Alexander",
    lastName: "White",
    email: "awhite@example.com",
  },
];
